services:
  bot:
    build: .
    container_name: mothman-bot
    depends_on:
      - redis
    ports:
      - "4000:4000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6380
    volumes:
      - mothman_data:/home/mothman
    restart: unless-stopped

  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    ports:
      - "6380:6380"
    volumes:
        - redis_data:/data
    restart: always
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  mothman_data:
  redis_data:
